import { useEffect, useRef, useState } from 'react';

/**
 * BACKEND TEAM INTEGRATION GUIDE:
 * 1. GET MESSAGES: Fetch chat history using sender (user.id) and receiver (teammate.id).
 * Endpoint Recommendation: GET /api/messages/:teammateId
 * 2. POST MESSAGE: Send { receiverId, text } to your API on handleSendMessage.
 * 3. SOCKET.IO:
 * - Listen for 'receive_message' to push new incoming messages to 'chatHistory'.
 * - Emit 'typing' status when handleInputChange is triggered.
 */

function ChatWidget({ teammate, onClose }) {
    const [message, setMessage] = useState('');
    const [isTyping, setIsTyping] = useState(false);
    const scrollRef = useRef(null);

    // --- STEP 1: LOAD INITIAL CHAT HISTORY ---
    const [chatHistory, setChatHistory] = useState(() => {
        // BACKEND TEAM: Replace localStorage logic with an initial API call or empty state
        const savedChat = localStorage.getItem(`chat_${teammate.id}`);
        return savedChat
            ? JSON.parse(savedChat)
            : [
                  {
                      id: 'welcome',
                      text: `Hi! This is ${teammate.name}. How can I help you?`,
                      sender: 'them',
                      time: new Date().toLocaleTimeString([], {
                          hour: '2-digit',
                          minute: '2-digit'
                      })
                  }
              ];
    });

    // --- STEP 2: HANDLE REAL-TIME UPDATES & SYNC ---
    useEffect(() => {
        // BACKEND TEAM:
        // 1. Fetch chat history from DB for this specific teammate.
        // 2. Initialize Socket.io listener here to catch real-time messages.

        const savedChat = localStorage.getItem(`chat_${teammate.id}`);
        if (savedChat) {
            setChatHistory(JSON.parse(savedChat));
        } else {
            setChatHistory([
                {
                    id: 'welcome',
                    text: `Hi! This is ${teammate.name}.`,
                    sender: 'them',
                    time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
                }
            ]);
        }
    }, [teammate.id, teammate.name]); // Fixed: Added teammate.name to dependencies

    useEffect(() => {
        // BACKEND TEAM: Once DB is connected, this localStorage sync should be removed.
        localStorage.setItem(`chat_${teammate.id}`, JSON.stringify(chatHistory));
        if (scrollRef.current) {
            scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
        }
    }, [chatHistory, teammate.id]);

    // --- STEP 3: SEND MESSAGE TO BACKEND ---
    const handleSendMessage = async (e) => {
        e.preventDefault();
        if (!message.trim()) return;

        const newMessage = {
            // BACKEND TEAM: 'id' should be generated by the database (UUID or ObjectId)
            id: Date.now(),
            text: message,
            sender: 'me',
            time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        };

        // BACKEND TEAM:
        // await axios.post('/api/messages/send', { receiverId: teammate.id, text: message });
        // socket.emit('send_message', { to: teammate.id, ...newMessage });

        setChatHistory((prev) => [...prev, newMessage]);
        setMessage('');
        setIsTyping(false);
    };

    const handleInputChange = (e) => {
        setMessage(e.target.value);
        setIsTyping(e.target.value.length > 0);
        // BACKEND TEAM: socket.emit('typing', { to: teammate.id });
    };

    return (
        <div className="fixed bottom-6 right-6 z-50 animate-in fade-in slide-in-from-bottom-4 duration-300">
            <div className="bg-white w-80 h-[450px] shadow-2xl rounded-t-xl flex flex-col border border-gray-300 overflow-hidden">
                {/* Header */}
                <div className="bg-red-500 p-4 text-white font-bold flex justify-between items-center shadow-md">
                    <div className="flex items-center gap-3 text-left min-w-0">
                        <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center overflow-hidden flex-shrink-0 border-2 border-white/20">
                            {teammate.image ? (
                                <img
                                    src={teammate.image}
                                    alt={teammate.name}
                                    className="w-full h-full object-cover"
                                />
                            ) : (
                                <span className="text-red-500 font-bold text-lg">
                                    {teammate.name.charAt(0)}
                                </span>
                            )}
                        </div>
                        <div className="flex flex-col min-w-0">
                            <span className="text-sm leading-tight truncate">{teammate.name}</span>
                            <span className="text-[10px] font-normal opacity-80 uppercase tracking-tighter truncate">
                                {teammate.role}
                            </span>
                        </div>
                    </div>
                    <button
                        type="button"
                        onClick={onClose}
                        className="hover:bg-red-600 p-1.5 rounded-full transition-colors flex-shrink-0"
                    >
                        ✕
                    </button>
                </div>

                {/* Chat History */}
                <div
                    ref={scrollRef}
                    className="flex-1 p-4 overflow-y-auto bg-gray-50 flex flex-col gap-4 scroll-smooth"
                >
                    {chatHistory.map((chat) => (
                        <div
                            key={chat.id}
                            className={`flex flex-col ${chat.sender === 'me' ? 'items-end' : 'items-start'}`}
                        >
                            <div
                                className={`p-2.5 rounded-xl text-xs shadow-sm max-w-[85%] break-words ${
                                    chat.sender === 'me'
                                        ? 'bg-red-500 text-white rounded-tr-none'
                                        : 'bg-white text-gray-800 border border-gray-200 rounded-tl-none'
                                }`}
                            >
                                {chat.text}
                            </div>
                            <span className="text-[9px] text-gray-400 mt-1 px-1">{chat.time}</span>
                        </div>
                    ))}
                    {isTyping && (
                        <div className="text-[10px] text-gray-400 italic animate-pulse">
                            Typing...
                        </div>
                    )}
                </div>

                {/* Input Area */}
                <div className="p-3 bg-white border-t">
                    <form className="flex gap-2" onSubmit={handleSendMessage}>
                        <input
                            type="text"
                            value={message}
                            onChange={handleInputChange}
                            placeholder="Type a message..."
                            className="flex-1 border border-gray-200 rounded-full px-4 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-red-500"
                        />
                        <button
                            type="submit"
                            className="bg-red-500 text-white p-2 rounded-full hover:bg-red-600 shadow-md flex items-center justify-center w-10 h-10 transition-transform active:scale-90"
                        >
                            <span className="block transform rotate-45 -mt-0.5 ml-0.5">➤</span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    );
}

export default ChatWidget;
